version: '3'
services:
  bot:
    build: .
    restart: always
    volumes:
      - "./logger:/home/Jashin-bot/logger/"
      - "./docker_conf:/home/Jashin-bot/common_conf/"
      - "./databases:/home/Jashin-bot/databases/"

  chatbot:
    build: ./apis
    restart: always
    volumes:
      - "./logger:/home/logger/"
      - "./docker_conf:/home/common_conf/"
    ports:
      - "8000:8080"
