version: '3'
services:
  bot:
    build: .
    restart: always
    volumes:
      - "./logger:/home/app/Jashin-bot/logger/"

  chatbot:
    build: ./apis
    restart: always
    volumes:
      - "./logger:/home/logger/"
    ports:
      - "8000:8080"

  test_deploy:
    image: debian:latest
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - "./logger:/home/logger/"
      
